# Project information
site_name: Textarium Docs
# site_url: https://squidfunk.github.io/mkdocs-material/
site_author: Stanislav Dobryakov
site_description: >-
  Textarium is a Python package for text processing

# Repository
repo_name: 6b656b/textarium
repo_url: https://github.com/6b656b/textarium

# Copyright
copyright: Copyright &copy; 2022 - 2030 Stanislav Dobryakov

# Theme
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings

# Page Tree
nav:
    - Installation: installation.md
    - Getting Started: getting-started.md
    - Code Reference:
        - Preprocessing: preprocessing-ref.md